import { Cookie } from "../types";

export const mockCookies: Cookie[] = [
  {
    id: "1",
    name: "_ga",
    value: "GA1.2.123456789.1234567890",
    domain: ".google.com",
    path: "/",
    expiry: "2026-01-01",
    secure: true,
    httpOnly: false,
  },
  {
    id: "2",
    name: "session_id",
    value: "abc123def456ghi789",
    domain: ".github.com",
    path: "/",
    expiry: "Session",
    secure: true,
    httpOnly: true,
  },
  {
    id: "3",
    name: "pref",
    value: "f1=50000000&f2=50000000",
    domain: ".youtube.com",
    path: "/",
    expiry: "2025-06-15",
    secure: true,
    httpOnly: false,
  },
  {
    id: "4",
    name: "auth_token",
    value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
    domain: "localhost",
    path: "/api",
    expiry: "2024-12-31",
    secure: false,
    httpOnly: true,
  },
  {
    id: "5",
    name: "theme",
    value: "dark",
    domain: ".example.com",
    path: "/",
    expiry: "2025-03-20",
    secure: false,
    httpOnly: false,
  },
  {
    id: "6",
    name: "csrf_token",
    value: "a1b2c3d4e5f6g7h8i9j0",
    domain: ".banking.com",
    path: "/",
    expiry: "Session",
    secure: true,
    httpOnly: true,
  },
];